layout: sidebar
style: light

plugins:
  - jekyll-octicons
  - jekyll-github-metadata
  - jemoji

permalink: /:year/:month/:day/:title/

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts"
    values:
      layout: "post"

projects:
  sort_by: pushed
  # sort_by options:
  #   - pushed
  #   - stars
  limit: 9
  exclude:
    archived: false
    forks: true
    projects:
    # - repo-name

social_media:
  # behance: your_username
  # dribbble: your_username
  facebook: psaibhaskar
  # hackerrank: your_username
  instagram: saibhaskar_royal
  # keybase: your_username
  linkedin: psaibhaskar24
  # mastodon: your_username
  # medium: your_username
  stackoverflow: 9797207
  telegram: Sai_bhaskar
  twitter: saibhaskar24
  # unsplash: your_username
  # vk: your_username
  website: http://saibhaskar24.github.io/
  youtube: UCBBQyNT5CCyUdXxtD5zi_Vw

topics:
  - name: Django
    web_url: https://github.com/topics/django
    image_url: https://user-images.githubusercontent.com/35323355/91919564-faf03900-ece3-11ea-9f4b-0740a52ed886.png

  - name: Node
    web_url: https://github.com/topics/node
    image_url: https://raw.githubusercontent.com/github/explore/80688e429a7d4ef2fca1e82350fe8e3517d3494d/topics/nodejs/nodejs.png
